finance_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from finance.views import DashboardView, TransactionsView
from finance_manager.views import Index
from users.views import UserLoginView, UserLogoutView, UserRegistrationView

urlpatterns = [
    path('', login_required(Index.as_view()), name='index'),
    path('admin/', admin.site.urls),

    path('', include('users.urls')),
    path('', include('finance.urls'))
]

users/urls.py
from django.urls import path
from users.views import UserLoginView, UserLogoutView, UserRegistrationView, ActivateUserView

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='user_login'),
    path('logout/', UserLogoutView.as_view(), name='user_logout'),
    path('register/', UserRegistrationView.as_view(), name='user_registration'),
    path(
        'activate/<str:uuid64>/<str:token>/',
        ActivateUserView.as_view(),
        name='activate'
    )
]

templates/users_auth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% block container-fluid %}

    {% endblock %}
</body>
</html>

templates/users_auth/login.html
{% extends 'users_auth/base.html' %}

{% block container-fluid %}

  <div class="center">
	  <form method="post" class="card" novalidate>
	  	{% csrf_token %}
	    <h2 class="text-center">Log in to your account</h2>
		{% for field in form %}
	    		{{ field.label_tag }}
	        	{{ field }}
	        	{% if field.errors %}
	        		<small>{{ field.errors|striptags }}</small>
	        	{% endif %}
		{% endfor %}

		<input type="submit" value="Login" class="btn btn-primary full-width">
		<hr>
		<p class="text-center">Forgot your password <a href="#">Reset Password</a></p>
		<p class="text-center">Don't have an account? <a href="{% url 'users:user_registration' %}">Join Now</a></p>
	</form>
</div>

{% endblock %}

templates/users_auth/registration_email.html
Hi, {{ user.first_name }}
<p>Please follow the link to complete the registration‹/p>

<a href="http://{{ domain }}{% url 'users:activate' uuid64=uid token=token %}">
    test mail registrate user
</a>

templates/users_auth/registration_form.html
{% extends 'users_auth/base.html' %}

{% block container-fluid %}
<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_ul }}
    <button type="submit">Click</button>
</form>
{% endblock %}