finance/urls.py
from django.urls import path

from .views import DashboardView, TransactionsView, add_transactions, CreateTransaction, add_account_to_list, get_account_list

app_name = 'finance'


urlpatterns = [
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('transactions/', TransactionsView.as_view(), name='transactions'),
    path('transactions/new/', add_transactions, name='new_transaction'),
    path('create_transaction_form/', CreateTransaction.as_view(), name='create-transaction'),


    path('create_account_form/', add_account_to_list, name='add_account'),
    path('get-account-list', get_account_list, name='get_account_list')
]

finance_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from finance.views import DashboardView, TransactionsView
from finance_manager.views import Index
from users.views import UserLoginView, UserLogoutView, UserRegistrationView

urlpatterns = [
    path('', login_required(Index.as_view()), name='index'),
    path('admin/', admin.site.urls),

    path('', include('users.urls')),
    path('', include('finance.urls'))
]

users/urls.py
from django.urls import path
from users.views import UserLoginView, UserLogoutView, UserRegistrationView, ActivateUserView

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='user_login'),
    path('logout/', UserLogoutView.as_view(), name='user_logout'),
    path('register/', UserRegistrationView.as_view(), name='user_registration'),
    path(
        'activate/<str:uuid64>/<str:token>/',
        ActivateUserView.as_view(),
        name='activate'
    )
]

finance/models/account.py
from django.contrib.auth.models import User
from django.db import models

from finance.models.budget import Budget
from finance.models.loan import Loan
from finance_manager import settings


class Currency(models.Model):
    CURRENCY_LIST = (
        ('usd', 'American Dollar'),
        ('eur', 'Euro'),
        ('pln', 'Polish zloty')
    )
    code = models.CharField(max_length=3, choices=CURRENCY_LIST, unique=True)

    def __str__(self):
        return self.code


class Account(models.Model):
    ACCOUNT_TYPES = (
        ('personal', 'Personal account'),
        ('business', 'Business account')
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=20, blank=False, null=False)
    main_currency = models.ForeignKey(Currency, on_delete=models.CASCADE)
    description = models.CharField(max_length=128, null=True, blank=True)
    is_active = models.BooleanField(default=True)
    account_type = models.CharField(max_length=20, null=False, blank=False,
                                    choices=ACCOUNT_TYPES)

    payment_methods = models.ManyToManyField('PaymentMethod',
                                             blank=True)
    loans = models.ManyToManyField(Loan, blank=True)
    budgets = models.ManyToManyField(Budget, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

finance/forms/account.py
from django import forms
from finance.models.account import Account


class AccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = '__all__'

templates/dashboard/account-form.html
<form hx-post="{{ request.path }}" class="modal-content">
  {% csrf_token %}
  <div class="modal-header">
    <h5 class="modal-title">Add account</h5>
  </div>
  <div class="modal-body">
    {{ form.as_p }}
  </div>
  <div class="modal-footer">
    <button type="button" data-bs-dismiss="modal">Cancel</button>
    <button type="submit">Save</button>
  </div>
</form>

templates/dashboard/account-str.html
<th>{{ account.name }}</th>

templates/dashboard/bar.html
<div class="left-bar">
    
    <div class="accounts-list" hx-trigger="load, accountListChanged from:body" hx-get="{% url 'finance:get_account_list' %}" hx-target="this" style="display: none;">
      <h5 class="accounts-header">Accounts</h5>
      <ul class="account-ul">
        <li>TEST ACCOUNT</li>
        <li>TEST ACCOUNT 1</li>
        <li>TEST ACCOUNT 2</li>
        <li>TEST ACCOUNT 3</li>
        {% for account in accounts %}
          
          <li>{{ account.name }}</li>
        {% endfor %}
      </ul>

      <a class="add-account" hx-get="{% url 'finance:add_account' %}" hx-target="#dialog">
        Add an account
      </a>
    </div>
    
    <h5 class="accounts-header">Accounts</h5>
    <div class="accounts-list">
      
      <ul class="account-ul">
        <li>Credit Agrecole</li>
        <li>Cash</li>
      </ul>
    </div>


    
    <h5 class="categories-header">Categories</h5>
    <div class="category-list">
      <ul>
        <li>
          <span class="material-symbols-outlined">
            fastfood
          </span>
          Food & Beverage
        </li>
        <li>
          <span class="material-symbols-outlined">
            kitchen
          </span>
          Groceries
        </li>
        <li>
          <span class="material-symbols-outlined">
            house
          </span>
          Household
        </li>
        <li>
          <span class="material-symbols-outlined">
            car_repair
          </span>
          Automobile
        </li>
      </ul>
    </div>
    <div class="more-categories">
      <a href="#">+5 more</a>
    </div>

    <div class="currency-selector">
      <select>
        <option value="USD">USD</option>
        <option value="UAH">UAH</option>
        <option value="PLN">PLN</option>
      </select>
    </div>
</div>

templates/dashboard/calendar.html
  <div class="calendar">
    <div class="calendar-scroll">
      <div class="calendar-dates" id="calendarDates">
        <!-- JavaScript will populate dates here -->
      </div>
    </div>
  </div>

templates/dashboard/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block container-fluid %}

<div class="content-wrapper">
    <div class="left-content">
      {% include 'dashboard/bar.html' %}
    </div>

    <div class="center-content">
        <div class="header-container">
            <h4 id="dashboard-header-center">Daily Transactions</h4>

            <div class="icon-container">
                <button class="calendar-button">
                <img id="calendar-icon" src="{% static 'img/dashboard/calendar.png' %}" alt="Calendar icon">
            </button>
            <button class="add-transaction-button" type="submit">
                <img id="new-transaction-icon" src="{% static 'img/dashboard/add.png' %}" alt="Add Icon">
            </button>
            </div>

        </div>
      <div class="search-bar">
          {% include 'dashboard/search-bar.html' %}
      </div>

      <div class="transaction-summary">
          {% include 'dashboard/total-daily-transactions.html' %}
      </div>

      <div class="daily-transactions">
          {% include 'dashboard/transaction-list.html' %}
      </div>
    </div>

    <div class="right-content">
      <div class="monthly-overview">
          {% include 'dashboard/monthly-overview.html' %}
      </div>
    </div>
  </div>
{% endblock %}

{% block modal %}

<div id="modal" class="modal fade">
  <div id="dialog" class="modal-dialog" hx-target="this"></div>
</div>
<script src="{% static 'js/calendar.js' %}"></script>
<script src="{% static 'js/add-account-modal.js' %}"></script>
{% endblock %}

templates/dashboard/main.html
{% extends 'base.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/dashboard.css' %}">


{% block content-fluid %}
<div class="content-wrapper">
    <div class="left-content">
      {% include 'dashboard/bar.html' %}
    </div>

    <div class="center-content">
      <button type="submit">New transaction</button>
      <div class="calendar">
        {% include 'dashboard/calendar.html' %}
      </div>

      <div class="transaction-summary">
        {% include 'dashboard/total-daily-transactions.html' %}
      </div>

      <div class="daily-transactions">
        {% include 'dashboard/transaction-list.html' %}
      </div>
    </div>

    <div class="right-content">
      <div class="monthly-overview">
        {% include 'dashboard/monthly-overview.html' %}
      </div>
    </div>
  </div>
{% endblock %}

templates/dashboard/monthly-overview.html
{% load static %}


<div class="monthly-overview">
  <h1 class="monthly-header">Monthly overview</h1>
  <div class="total-cards">
    <div class="expense-card">
      <h1 class="card-header">Expense</h1>
      <img class="card-image" src="{% static 'img/dashboard/income.png' %}" alt="income">
      <h1 class="month-expense-total">-250$</h1>
      <h1 class="daily-expense-total">-25.55</h1>
    </div>
    <div class="income-card">
      <h1 class="card-header">Income</h1>
      <img class="card-image" src="{% static 'img/dashboard/expenses.png' %}" alt="expenses">
      <h1 class="month-income-total">+550$</h1>
      <h1 class="daily-income-total">+25.55</h1>
    </div>
  </div>
</div>



<div class="summary-expense">
  <h3>Expenses by category</h3>
  <div class="expense-cards">
    <div class="card-1">
      <span class="name">
        Food
      </span>
      <div class="info">
        <span class="total-count">
          133.95$
        </span>
        <span class="percent">
          55%
        </span>
      </div>
    </div>
    <div class="card-2">
    </div>
    <div class="card-3">
    </div>
  </div>
</div>


</div>

templates/dashboard/search-bar.html
<input id="transaction-search" type="search" name="q" placeholder="Search anything..."/>

templates/dashboard/total-daily-transactions.html
<div class="transaction-summary">
  <div class="daily-summary-table">
    <div class="left-column">
      <div class="label">Total Expense</div>
      <div class="value">1200$</div>
    </div>
    <div class="centre-column">
      <div class="label">Total Income</div>
      <div class="value">1200$</div>
    </div>
    <div class="right-column">
      <div class="label">Total Net</div>
      <div class="value">1300$</div>
    </div>
  </div>
</div>

templates/dashboard/transaction-list.html
<table class="table table-striped">
  <thead style="display: none;">
    <tr>
      <th scope="col">Category</th>
      <th scope="col">Amount</th>
      <th scope="col">Payment Method</th>
      <th scope="col">Create at</th>
    </tr>
  </thead>
  <tbody>
{% for transaction in transactions %}
    <tr>
      <div class="transactions">
        <div class="transaction-icon">

          <span class="material-symbols-outlined">
            phone_iphone
          </span>
          
        </div>
        <div>
          <ul class="transaction-title">
            {{transaction.category}}
          </ul>
          <ul class="transaction-data">
            {{transaction.created_at}}
          </ul>
        </div>
        <div class="transaction-price">
          {{transaction.amount}}
        </div>
      </div>
    </tr>
{% endfor %}
  </tbody>
</table>