finance/urls.py
from django.urls import path

from .views import DashboardView, TransactionsView, add_transactions, CreateTransaction, add_account_to_list, get_account_list

app_name = 'finance'


urlpatterns = [
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('transactions/', TransactionsView.as_view(), name='transactions'),
    path('transactions/new/', add_transactions, name='new_transaction'),
    path('create_transaction_form/', CreateTransaction.as_view(), name='create-transaction'),


    path('create_account_form/', add_account_to_list, name='add_account'),
    path('get-account-list', get_account_list, name='get_account_list')
]

finance_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from finance.views import DashboardView, TransactionsView
from finance_manager.views import Index
from users.views import UserLoginView, UserLogoutView, UserRegistrationView

urlpatterns = [
    path('', login_required(Index.as_view()), name='index'),
    path('admin/', admin.site.urls),

    path('', include('users.urls')),
    path('', include('finance.urls'))
]

users/urls.py
from django.urls import path
from users.views import UserLoginView, UserLogoutView, UserRegistrationView, ActivateUserView

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='user_login'),
    path('logout/', UserLogoutView.as_view(), name='user_logout'),
    path('register/', UserRegistrationView.as_view(), name='user_registration'),
    path(
        'activate/<str:uuid64>/<str:token>/',
        ActivateUserView.as_view(),
        name='activate'
    )
]

finance/models/transaction.py
from django.contrib.auth.models import User
from django.db import models

from finance.models.account import Currency
from finance.models.wallet import PaymentMethod
from finance_manager import settings


class Description(models.Model):
    value = models.TextField(max_length=100)

    def __str__(self):
        return self.value


class TransactionType(models.Model):
    TRANSACTION_TYPES = (
        ('income', 'Income'),
        ('expense', 'Expense')
    )
    name = models.CharField(max_length=50, choices=TRANSACTION_TYPES)

    def __str__(self):
        return str(self.name).capitalize()


class TransactionCategory(models.Model):
    name = models.CharField(max_length=50)
    is_required = models.BooleanField(default=False)
    is_loan = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.name}'


class Transaction(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )
    category = models.ForeignKey(
        TransactionCategory,
        on_delete=models.DO_NOTHING
    )
    transaction_type = models.ForeignKey(
        TransactionType,
        on_delete=models.DO_NOTHING
    )
    amount = models.DecimalField(decimal_places=2, max_digits=10)
    description = models.ForeignKey(
        Description,
        on_delete=models.DO_NOTHING,
        null=True, blank=True
    )
    payment_method = models.ForeignKey(
        PaymentMethod,
        on_delete=models.CASCADE
    )
    currency = models.ForeignKey(
        Currency,
        on_delete=models.DO_NOTHING,
        related_name='dashboard'
    )
    created_at = models.DateTimeField(auto_now_add=True)

finance/forms/transaction.py
from django import forms

from finance.models import Transaction


class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction

        fields = (
            'category',
            'transaction_type',
            'amount',
            'description',
            'payment_method',
            'currency'
        )

        """widgets = {
            'category': forms.TextInput(attrs={'class': 'form-control'}),
            'transaction_type': forms.TextInput(attrs={'class': 'form-control'}),
            'amount': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.TextInput(attrs={'class': 'form-control'}),
            'payment_method': forms.TextInput(attrs={'class': 'form-control'}),
            'currency': forms.TextInput(attrs={'class': 'form-control'}),
        }"""

templates/transactions/add-transactions.html
{% extends 'base.html' %}

{% block container-fluid %}
{% load static %}


<div class="my-4">
  <button type="button" class="btn btn-success me-2"
      hx-get="{% url 'finance:create-transaction' %}"
      hx-target="#transaction-forms"
      hx-swap="beforeend">+ Add form</button>
  <button type="button" class="btn btn-primary" id="submit-all">Sumbit all</button>
</div>

<div id="transaction-forms">
      {% include 'transactions/form.html' %}
</div>


{% endblock %}

templates/transactions/all-transactions.html
<tr>
    <th>User</th>
    <th>Category</th>
    <th>Transaction Type</th>
    <th>Amount</th>
    <th>Description</th>
    <th>Payment Method</th>
    <th>Currency</th>
    <th>Created At</th>
</tr>
{% for transaction in transactions %}
<tr>
    <td>{{ transaction.user }}</td>
    <td>{{ transaction.category }}</td>
    <td>{{ transaction.transaction_type }}</td>
    <td>{{ transaction.amount }}</td>
    <td>{{ transaction.description }}</td>
    <td>{{ transaction.payment_method }}</td>
    <td>{{ transaction.currency }}</td>
    <td>{{ transaction.created_at }}</td>
</tr>
{% endfor %}

templates/transactions/form.html
<form
    hx-post="{% url 'finance:create-transaction' %}"
    hx-target="#transactions-list"
    hx-swap="afterend"
    hx-on="htmx:afterRequest: this.remove()"
    hx-trigger="click from:#submit-all"
>
    <div class="col-3 align-self-end">
        <button type="button" class="btn btn-danger"
            hx-on="click: this.closest('form').remove()">
            Cancel
        </button>
    </div>

    <div class="table-as-form">
        <table class="table table-striped table-light">
          <tbody>
            <tr>
              {% for field in form %}
                <th>{{ field.label_tag }}</th>
                <td>{{ field }}</td>
              {% endfor %}
            </tr>
          </tbody>
        </table>
    </div>
</form>

templates/transactions/main.html
{% extends 'base.html' %}
{% load static %}

<link rel="stylesheet" href="{% static 'css/transactions.css' %}">

{% block content-fluid %}

<div class="transactions-list">
    {% include 'transactions/table-filter.html' %}
    <table class="table table-striped table-dark">
        {% include 'transactions/all-transactions.html' %}
    </table>
</div>

{% endblock %}

templates/transactions/new-transaction.html
{% extends 'base.html' %}

{% block container-fluid %}


<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_ul }}
    <button type="submit">Click</button>
</form>


{% endblock %}

templates/transactions/transaction.html
<tr id="transaction-{{ transaction.id }}">
  <td>{{ transaction.category }}</td>
  <td>{{ transaction.transaction_type }}</td>
  <td>{{ transaction.created_at }}</td>
  <td>{{ transaction.amount }}</td>
</tr>

templates/transactions/transactions.html
{% extends 'base.html' %}
{% load static %}

<link rel="stylesheet" href="{% static 'css/transactions.css' %}">

{% block container-fluid %}

<div class="transactions-list">
    <table class="table table-striped table-dark">
        {% include 'transactions/all-transactions.html' %}
    </table>
</div>

{% endblock %}